bonjour_root/bonjour/urls.py
from django.contrib import admin
from django.urls import include, path
from crm import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls, name = 'admin'),
    path('', views.first_page, name = 'home'),
    path('thanks/', views.thanks_page, name = 'thanks_page'),
    path('bronze/', include('bronze.urls'), name='bronze'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bonjour_root/bronze/urls.py
from django.urls import path
from . import views

app_name = 'bronze'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

bonjour_root/bronze/models.py
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200, verbose_name='Вопрос')
    pub_date = models.DateTimeField(auto_now=True, verbose_name='Дата публикации')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    class Meta:
        verbose_name = 'Вопросы'
        verbose_name_plural = 'Вопросы'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='Вопрос')
    choice_text = models.CharField(max_length=200, verbose_name='Текст ответа')
    votes = models.IntegerField(default=0,verbose_name='Голосов')

    def __str__(self):
        return self.choice_text

    class Meta:
        verbose_name = 'Выбор'
        verbose_name_plural = 'Выбор'

bonjour_root/cms/models.py
from django.db import models

class CmsSlider(models.Model):
    cms_img = models.ImageField(upload_to='sliderimg/')
    cms_title = models.CharField(max_length=200, verbose_name='Заголовок')
    cms_text = models.CharField(max_length=200, verbose_name='Текст')
    cms_css = models.CharField(max_length=200, null=True, default='-', verbose_name='CSS класс')

    def __str__(self):
        return self.cms_title

    class Meta:
        verbose_name = 'Слайд'
        verbose_name_plural = 'Слайды'

bonjour_root/crm/models.py
from django.db import models

class StatusCrm(models.Model):
    Status_name = models.CharField(max_length=200, verbose_name='Название статуса')

    def __str__(self):
        return self.Status_name

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

class Order(models.Model):
    data = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=200, verbose_name='Имя')
    phone = models.CharField(max_length=200, verbose_name='Телефон')
    status = models.ForeignKey(StatusCrm, on_delete=models.PROTECT, null=True, blank=True, verbose_name='Статус')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

class ComentCrm(models.Model):
    coment_binding = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заявка')
    coment_text = models.TextField(verbose_name='Текст комментария')
    coment_data = models.DateTimeField(auto_now=True, verbose_name='Дата создания')

    def __str__(self):
        return self.coment_text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

bonjour_root/price/models.py
from django.db import models


class PriceCard(models.Model):
    pc_value = models.CharField(max_length=20, verbose_name='Цена')
    pc_description = models.CharField(max_length=200, verbose_name='Описание')

    def __str__(self):
        return self.pc_value

    class Meta:
        verbose_name = 'Цены'
        verbose_name_plural = 'Цены'


class PriceTable(models.Model):
    pt_title = models.CharField(max_length=200, verbose_name='Услуга')
    pt_old_price = models.CharField(max_length=200, verbose_name='Старая цена')
    pt_new_price = models.CharField(max_length=200, verbose_name='Новая цена')

    def __str__(self):
        return self.pt_title

    class Meta:
        verbose_name = 'Услугу'
        verbose_name_plural = 'Услуги'

bonjour_root/telebot/models.py
from django.db import models

class TeleSettings(models.Model):
    tg_token = models.CharField(max_length=200, verbose_name='Токен')
    tg_chat = models.CharField(max_length=200, verbose_name='Чат')
    tg_message = models.TextField(verbose_name='Текст сообщения')

    def __str__(self):
        return self.tg_chat

    class Meta:
        verbose_name = 'Настройку'
        verbose_name_plural = 'Настройки'

bonjour_root/crm/forms.py
from django import forms

class OrderForm(forms.Form):
    name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))

bonjour_root/bronze/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Choice, Question
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    temlate = loader.get_template('bronze/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    output = ', '.join([q.question_text for q in latest_question_list])
    return HttpResponse(temlate.render(context,request))

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render (request, 'bronze/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'bronze/results.html', {'question':question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'bronze/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('bronze:results', args=(question.id,)))

class IndexView(generic.ListView):
    template_name = 'bronze/index.html'
    context_object_name = 'latest_question_list'

    def get_ordering(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'bronze/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'bronze/results.html'


def vote(request, question_id):
    ... # same as above, no changes needed.

bonjour_root/cms/views.py
from django.shortcuts import render

# Create your views here.

bonjour_root/crm/views.py
from django.shortcuts import render
from .models import Order
from .forms import OrderForm
from cms.models import CmsSlider
from price.models import PriceCard, PriceTable
from telebot.sendmessage import sendTelegram

def first_page(request):
    slider_list = CmsSlider.objects.all()
    pc_1 = PriceCard.objects.get(pk=1)
    pc_2 = PriceCard.objects.get(pk=2)
    pc_3 = PriceCard.objects.get(pk=3)
    price_table = PriceTable.objects.all()
    form = OrderForm
    dict_obj = { 'slider_list': slider_list,
                 'pc_1': pc_1,
                 'pc_2': pc_2,
                 'pc_3': pc_3,
                 'price_table': price_table,
                 'form': form,
                 }
    return render(request, './index.html', dict_obj)

def thanks_page(request):
    if request.POST:
        name = request.POST['name']
        phone = request.POST['phone']
        element = Order(name = name, phone = phone)
        element.save()
        sendTelegram(tg_name=name, tg_phone=phone)
        return render(request, './thanks.html', {'name': name})

    else:
        return render(request, './thanks.html')

bonjour_root/price/views.py
from django.shortcuts import render

bonjour_root/telebot/views.py
from django.shortcuts import render

# Create your views here.

bonjour_root/templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'external.css' %}" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Bonjour</title>
  </head>
  <body>
	<nav class="navbar navbar-light bg-light container">
	  <a class="navbar-brand logo-top" href="{% url 'home' %}">
	    <img src="{% static 'img/Logo.png' %}" width="40" height="40" class="d-inline-block align-top" alt="" loading="lazy">
	    Bonjour
	  </a>
	  <div class="contact-top">
                <a class="whatsapp-number" href="https://web.whatsapp.com/"></a>
                <a class="telegram-number" href="https://t.me/"></a>
              <a class="phone-number text-dark" href="tel:+74957777777">
              	<h5>+7(927)-959-19-95</h5></a>
      </div>
	</nav>

{% block index %}

{% endblock %}

{% block thanks %}

{% endblock %}
    	<footer>
  		<div class="container">
  			<nav class="navbar navbar-light bg-light container">
			    <a class="navbar-brand logo-top" href="{% url 'home' %}">
			    	<img src="{% static 'img/Logo.png' %}" width="40" height="40" class="d-inline-block align-top" alt="" loading="lazy">
			    	Bonjour
			    </a>
	  			<div class="contact-top">
	                <a class="whatsapp-number" href="https://web.whatsapp.com/"></a>
	                <a class="telegram-number" href="https://t.me/"></a>
	              	<a class="phone-number text-dark" href="tel:+74957777777">
	              	<h5>+7(927)-959-19-95</h5></a>
      			</div>
			</nav>
  		</div>
  	    </footer>




    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

bonjour_root/templates/bronze.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

bonjour_root/templates/bronze/detail.html
<form action="{% url 'bronze:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

bonjour_root/templates/bronze/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'bronze:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

bonjour_root/templates/bronze/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} Голосовать {{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'bronze:detail' question.id %}">Голосовать снова?</a>

bonjour_root/templates/carusel.html
{% load static %}
	<section>
  		<div id="carouselExampleCaptions" class="carousel slide container" data-ride="carousel">
		  <div class="carousel-inner">
			{% for slide in slider_list %}
		    <div class="carousel-item {{ slide.cms_css }}">
		      <img src="{{ slide.cms_img.url }}" class="d-block w-100"  alt="...">
		      <div class="carousel-caption d-none d-md-block">
		        <h5 class="slaider_h">{{ slide.cms_title }}</h5>
		        <p class="slaider_p">{{ slide.cms_text }}</p>
		      </div>
		    </div>
			{% endfor %}

		  </div>
		  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
		    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
		    <span class="carousel-control-next-icon" aria-hidden="true"></span>
		    <span class="sr-only">Next</span>
		  </a>
		</div>
  	</section>

bonjour_root/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block index %}

	<!-- карусель -->
	{% include 'carusel.html' %}
  	<!-- Карточки -->
	{% include 'prices.html' %}
  	<!-- форма -->
  	<section>
  		<div class="container class_form">
  			<h1 class="text-3">Оставь заявку и получи услугу</h1>
  			<div class="row justify-content-center">
  			<form action="{% url 'thanks_page' %}" method="POST" style="width: 50%;">
				{% csrf_token %}
			  <div class="form-group row">
			    <label for="inputEmail3" class="col-sm-2 col-form-label">Имя</label><br>
			      {{ form.name }}
			    <div class="">
			    </div>
			  </div>
			  <div class="form-group row">
			    <label for="inputEmail3" class="col-sm-2 col-form-label">Телефон</label><br>
				  {{ form.phone }}
			    <div class="">
			    </div>
			  </div>
			  <div style="float: right;" class="form-group row">
			      <button type="submit" class="btn btn-success">ОСТАВИТЬ ЗАЯВКУ</button>
			  </div>
			</form>
			</div>
  		</div>
  	</section>
{% endblock %}

bonjour_root/templates/prices.html
  	<section>
  		<div class="container">
  			<h1 class="text-3">Подарочные сертификаты</h1>
  			<div class="row justify-content-center">
  				<div class="card product_card" style="width: 18rem; background-color: #cd7f32;">
				  <div class="card-body">
				    <h5 class="card-title">BRONZE</h5>
				    <p class="card-text">Можно реализовать подарочную систему</p>
				    <h3>{{ pc_1 }} руб.</h3>
				  </div>
				</div>
				<div class="card product_card" style="width: 18rem; background-color: #c0c0c0;">
				  <div class="card-body">
				    <h5 class="card-title">SILVER</h5>
				    <p class="card-text">Можно реализовать подарочную систему</p>
				    <h3>{{ pc_2 }} руб.</h3>
				  </div>
				</div>
				<div class="card product_card" style="width: 18rem; background-color: #ffd700;">
				  <div class="card-body">
				    <h5 class="card-title">GOLD</h5>
				    <p class="card-text">Можно реализовать подарочную систему</p>
				    <h3>{{ pc_3 }} руб.</h3>
				  </div>
				</div>
  			</div>
  		</div>
  	</section>

  	<section>
  		<div class="container">
  			<h1 class="text-3">Цены на услуги</h1>
  			<table class="table table_one">
			  <thead class="thead-dark">
			    <tr>
			      <th scope="col">Услуга</th>
			      <th scope="col">Старая цена</th>
			      <th scope="col">Новая цена</th>
			    </tr>
			  </thead>
			  <tbody>
			  {% for obj in price_table %}
			    <tr>
			      <td>{{ obj.pt_title }}</td>
			      <td><del>{{ obj.pt_old_price }}</del></td>
			      <td>{{ obj.pt_new_price }}</td>
			    </tr>
			  {% endfor %}
			  </tbody>
			</table>
  		</div>
  	</section>

bonjour_root/templates/thanks.html
{% extends 'base.html' %}
{% load static %}

{% block thanks %}
	<!-- Спасибо -->
  	<section>
		{% if name %}
  		<div class="container">
  			<CENTER style = 'margin-top: 35%; margin-bottom: 35%;'><h1>{{ name }}, спасибо за заявку!</h1></CENTER>
  		</div>
		{% else %}
		<div class="container">
  			<CENTER style = 'margin-top: 35%; margin-bottom: 35%;'><h1>Cпасибо страница!</h1></CENTER>
  		</div>
		{% endif %}
  	</section>
  	<!-- Спасибо -->
{% endblock %}